apiVersion: v1
kind: Secret
metadata:
  name: litellm-secrets
type: Opaque
stringData:
  airs_apikey: "w49TtA04gyaqcxHlRYnW78GuuvWtRh55nIgQ1ECiPQ8CK9A3"
data:
  secret.json: "ewogICJhY2NvdW50IjogIiIsCiAgImNsaWVudF9pZCI6ICI3NjQwODYwNTE4NTAtNnFyNHA2Z3BpNmhuNTA2cHQ4ZWp1cTgzZGkzNDFodXIuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLAogICJjbGllbnRfc2VjcmV0IjogImQtRkw5NVExOXE3TVFtRnBkN2hIRDBUeSIsCiAgInJlZnJlc2hfdG9rZW4iOiAiMS8vMDY1R0llLTVTSUFZTUNnWUlBUkFBR0FZU053Ri1MOUlyQVJDaVF2UXlzeHcySzk3OW5rdEdiOEFjOWk5b0JiSkt6ZW9lLXE3a1A4RmpFYy1tV2c3UTlOLW1ySENRckdkWlJOSSIsCiAgInR5cGUiOiAiYXV0aG9yaXplZF91c2VyIiwKICAidW5pdmVyc2VfZG9tYWluIjogImdvb2dsZWFwaXMuY29tIgp9"